CREATE TABLE "PS"."EC_PSM_ASSETFOLDER" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PARENTASSETFOLDER_ID" NUMBER(19,0), 
	"LASTMODIFIED_BY" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"LASTMODIFIED_TS" TIMESTAMP (0) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"CREATED_TS" timestamp (0) not null enable, 
	 CONSTRAINT "EC_PSM_ASSETFOLDER_PK" PRIMARY KEY ("ID")
  using index tablespace "PS_INDEX1"  enable, 
	constraint "EC_PSM_ASSETFOLDER_FK1" foreign key ("PARENTASSETFOLDER_ID")
	  REFERENCES "PS"."EC_PSM_ASSETFOLDER" ("ID") ENABLE
   ) TABLESPACE "PS_DATA1" ;

  create index "PS"."EC_PSM_ASSETFOLDER_FKFIX" on "PS"."EC_PSM_ASSETFOLDER" ("PARENTASSETFOLDER_ID") 
  TABLESPACE "PS_INDEX1" ;


CREATE TABLE "PS"."EC_PSM_ASSET" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ASSETFOLDER_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MIME_TYPE" VARCHAR2(50 CHAR), 
	"IS_BINARY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"LASTMODIFIED_BY" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"LASTMODIFIED_TS" TIMESTAMP (0) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"CREATED_TS" timestamp (0) not null enable, 
	 CONSTRAINT "EC_PSM_ASSET_PK" PRIMARY KEY ("ID")
  using index tablespace "PS_INDEX1"  enable,  
	 constraint "EC_PSM_ASSET_FK1" foreign key ("ASSETFOLDER_ID")
	  REFERENCES "PS"."EC_PSM_ASSETFOLDER" ("ID") ENABLE
   ) TABLESPACE "PS_DATA1" ;

  CREATE INDEX "PS"."EC_PSM_ASSET_FKFIX" ON "PS"."EC_PSM_ASSET" ("ASSETFOLDER_ID") 
  tablespace "PS_INDEX1" ;
  
  


CREATE TABLE "PS"."EC_PSM_ASSETCONTENT" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ASSET_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STATUS" CHAR(1 CHAR) NOT NULL ENABLE, 
	"BLOB_CONTENT" BLOB, 
	"CLOB_CONTENT" NCLOB, 
	"LASTMODIFIED_BY" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"LASTMODIFIED_TS" TIMESTAMP (0) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"CREATED_TS" timestamp (0) not null enable, 
	 CONSTRAINT "EC_PSM_ASSETCONTENT_PK" PRIMARY KEY ("ID")
  using index tablespace "PS_INDEX1"  enable, 
	 constraint "EC_PSM_ASSETCONTENT_STATUS_CHK" check (status in ('A','P','D')) enable, 
	 constraint "EC_PSM_ASSETCONTENT_FK1" foreign key ("ASSET_ID")
	  REFERENCES "PS"."EC_PSM_ASSET" ("ID") ENABLE
   ) TABLESPACE "PS_DATA1" 
 LOB ("BLOB_CONTENT") STORE AS BASICFILE (
  TABLESPACE "PS_DATA1" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CLOB_CONTENT") STORE AS BASICFILE (
  TABLESPACE "PS_DATA1" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE INDEX "PS"."EC_PSM_ASSETCONTENT_FKFIX" ON "PS"."EC_PSM_ASSETCONTENT" ("ASSET_ID") 
  TABLESPACE "PS_INDEX1" ;
  
  CREATE OR REPLACE PUBLIC SYNONYM EC_PSM_ASSETCONTENT
  FOR PS.EC_PSM_ASSETCONTENT;
  CREATE OR REPLACE PUBLIC SYNONYM EC_PSM_ASSET
  FOR PS.EC_PSM_ASSET;
  CREATE OR REPLACE PUBLIC SYNONYM EC_PSM_ASSETFOLDER
  FOR PS.EC_PSM_ASSETFOLDER;
  /
  
  