CREATE OR REPLACE PROCEDURE PS.CAS_EC_INC_CODE_SYNC_PROC 
IS 
  V_ID_1 NUMBER;  
  V_ID_2 NUMBER;  
BEGIN
  -- GRAB INCIDENT LOOKUP CODES FROM ENTERPRISE CONTROLLER
  FOR remote_code IN
    (
      SELECT 
        ILC.LU_CODE_ID,ILC.CODE_TYPE,ILC.INCIDENT_CATEGORY,ILC.STATE_AGGREGATE_RPT_CODE,ILC.APPLICATION_DISPLAY_ORDER ILCADO,
        ILSC.LU_SUB_CODE_ID,ILSC.SUB_CATEGORY,ILSC.SEVERITY,ILSC.IS_STATE_REPORTABLE_FLG,
        ILSC.IS_POLICE_REPORTABLE_FLG,ILSC.STATE_DETAIL_REPORT_CODE,ILSC.APPLICATION_DISPLAY_ORDER ILSCADO,
        ILSC.SHORT_DESC,ILSC.LONG_DESC,ILSC.EFFECTIVE_BEGIN_DT,ILSC.EFFECTIVE_END_DT,ILSC.STATUS,
        ILSC.RESTRICTED,ILSC.COMMENT_ENABLE_STATE,ILSC.PARENT_LU_SUB_CODE_ID,ILSC.DATATYPE_ATTRIBUTE
      FROM INCIDENT_LU_CODE@DBL_ENTCON ILC
      INNER JOIN INCIDENT_LU_SUB_CODE@DBL_ENTCON ILSC ON ILC.LU_CODE_ID = ILSC.LU_CODE_ID
      WHERE ILC.CODE_TYPE||ILC.INCIDENT_CATEGORY NOT IN (SELECT LOCAL_CODE.CODE_TYPE||LOCAL_CODE.INCIDENT_CATEGORY FROM INCIDENT_LU_CODE LOCAL_CODE)
    )
  LOOP
    --ASSIGN SEQUENCE VARIABLES
    V_ID_1 := SEQ_INLUCD.NEXTVAL;
    V_ID_2 := SEQ_INSBCD.NEXTVAL;
    --INSERT MAIN LOOKUP TABLE RECORDS
    INSERT INTO INCIDENT_LU_CODE
      (LU_CODE_ID,CODE_TYPE,INCIDENT_CATEGORY,STATE_AGGREGATE_RPT_CODE,APPLICATION_DISPLAY_ORDER)
    VALUES 
      (V_ID_1,remote_code.CODE_TYPE,remote_code.INCIDENT_CATEGORY,
      remote_code.STATE_AGGREGATE_RPT_CODE,remote_code.ILCADO);
    --INSERT SUB LOOKUP TABLE RECORDS
    INSERT INTO incident_lu_sub_code 
      (LU_SUB_CODE_ID,SUB_CATEGORY,LU_CODE_ID,SEVERITY,IS_STATE_REPORTABLE_FLG,
      IS_POLICE_REPORTABLE_FLG,STATE_DETAIL_REPORT_CODE,APPLICATION_DISPLAY_ORDER,
      SHORT_DESC,LONG_DESC,EFFECTIVE_BEGIN_DT,EFFECTIVE_END_DT,STATUS,
      RESTRICTED,COMMENT_ENABLE_STATE,PARENT_LU_SUB_CODE_ID,DATATYPE_ATTRIBUTE)
    VALUES
      (v_id_2,remote_code.SUB_CATEGORY,v_id_1,remote_code.SEVERITY,remote_code.IS_STATE_REPORTABLE_FLG,
      remote_code.IS_POLICE_REPORTABLE_FLG,remote_code.STATE_DETAIL_REPORT_CODE,remote_code.ILSCADO,
      remote_code.SHORT_DESC,remote_code.LONG_DESC,remote_code.EFFECTIVE_BEGIN_DT,remote_code.EFFECTIVE_END_DT,remote_code.STATUS,
      remote_code.RESTRICTED,remote_code.COMMENT_ENABLE_STATE,remote_code.PARENT_LU_SUB_CODE_ID,remote_code.DATATYPE_ATTRIBUTE);
  END LOOP;
END CAS_EC_INC_CODE_SYNC_PROC;